id: kita_alltag
title: "Kita Alltag"
description: "Der tägliche Wahnsinn in der Kindertagesstätte bringt immer neue Überraschungen."
trigger:
  after_cards: 20
  requires_story_completed: [geburtstag_einladung]
trigger_cards:
  # This card appears in main deck and can trigger the kindergarten daily life story
  - id: kita_start
    image: kindergarten-teacher.png
    description: "Ihr Kind geht jetzt in die Kita. 'Mama, ich mag die Kita!' Aber der Alltag dort bringt neue Herausforderungen mit sich."
    left:
      label: "Eng mit Erziehern zusammenarbeiten"
      effects:
        - kinder_glueck: +15
        - eltern_nerven: -10
        - kinder_gesundheit: +10
      accept_story: kita_alltag
    right:
      label: "Kind wird sich schon einleben"
      effects:
        - eltern_nerven: +5
        - kinder_glueck: +5
      reject_story: kita_alltag
story_cards:
  # These cards only appear when the kindergarten daily life story is accepted
  - id: noro_virus_kita
    image: kindergarten-teacher.png
    description: "Noro-Virus in der Kita! Drei Kinder sind schon betroffen. Ihr Kind war gestern den ganzen Tag dort."
    left:
      label: "Vorsichtshalber zu Hause lassen"
      effects:
        - eltern_nerven: -15
        - kinder_gesundheit: +15
        - geld: -18
    right:
      label: "Normal zur Kita bringen"
      effects:
        - kinder_gesundheit: -10
        - eltern_nerven: +5
    probability: 0.40
    mix_in_next: 18
  - id: kind_krank_abholen
    image: kindergarten-teacher.png
    description: "Anruf von der Kita: 'Ihr Kind hat Fieber und muss abgeholt werden.' Sie sind mitten in einem wichtigen Meeting."
    left:
      label: "Sofort abholen"
      effects:
        - eltern_nerven: -25
        - kinder_gesundheit: +20
        - geld: -30
    right:
      label: "Partner/Familie anrufen"
      effects:
        - eltern_nerven: -15
        - kinder_gesundheit: +10
        - geld: -15
    probability: 0.65
    mix_in_next: 22
  - id: kind_hat_gebissen
    image: kindergarten-teacher.png
    description: "Schwieriges Gespräch mit der Erzieherin: 'Ihr Kind hat heute zwei andere Kinder gebissen.' Das ist peinlich."
    left:
      label: "Verhalten zu Hause besprechen"
      effects:
        - eltern_nerven: -20
        - kinder_glueck: -15
        - kinder_gesundheit: +10
    right:
      label: "Professionelle Beratung suchen"
      effects:
        - geld: -25
        - eltern_nerven: -10
        - kinder_gesundheit: +20
    probability: 0.30
    mix_in_next: 25
  - id: kitafest_mitbringliste
    image: kindergarten-teacher.png
    title: "Frau Müller bittet um Mitbringsel"
    description: "Für das Kitafest sollen Sie etwas mitbringen. Zur Auswahl stehen: aufwendiger Salat mit Dekoration oder einfach nur ein gekauftes Baguette."
    left:
      label: "Ja, aufwendiger Salat + Deko"
      effects:
        - geld: -12
        - kinder_glueck: +15
        - eltern_nerven: -20
        - kinder_gesundheit: +10
    right:
      label: "Nur ein gekauftes Baguette"
      effects:
        - geld: -5
        - kinder_glueck: +10
        - eltern_nerven: +15
        - kinder_gesundheit: +5
    probability: 0.60
    mix_in_next: 20
  - id: personalausfall_kita
    image: kindergarten-teacher.png
    title: "Frau Schmidt informiert über Personalausfall"
    description: "Wegen Personalausfall muss die Kita früher schließen. Sie müssen Ihre Arbeitszeit anpassen oder eine andere Lösung finden."
    left:
      label: "Arbeitszeit anpassen, irgendwie durchwurschteln"
      effects:
        - geld: -15
        - kinder_glueck: +8
        - eltern_nerven: -20
        - kinder_gesundheit: +5
    right:
      label: "Beschweren und Ausweichlösung fordern"
      effects:
        - geld: -15
        - kinder_glueck: +5
        - eltern_nerven: -15
        - kinder_gesundheit: +10
    probability: 0.70
    mix_in_next: 15