id: schlangen_abenteuer
title: "Das Schlangen-Abenteuer"
description: "Eine Geschichte über den Wunsch nach einem ungewöhnlichen Haustier und die Konsequenzen."
trigger:
  after_cards: 2
trigger_cards:
  # These cards are added to the main deck and can trigger the story
  - id: schlange_wunsch
    image: kid.png
    description: "Ihr Kind kommt vom Nachbarn zurück und bittet um eine Haustierschlange. 'Alle anderen haben auch coole Haustiere! Eine Schlange ist so interessant!'"
    left:
      label: "Eine Schlange? Warum nicht..."
      effects:
        - geld: -80
        - kinder_glueck: +25
        - eltern_nerven: -15
      accept_story: schlangen_abenteuer
    right:
      label: "Definitiv nein! Vielleicht ein Goldfish?"
      effects:
        - kinder_glueck: -15
        - geld: -20
        - eltern_nerven: +5
      reject_story: schlangen_abenteuer
story_cards:
  # These cards are only added when the story is accepted
  - id: schlangen_begegnung
    image: kid.png
    description: "Die Schlange ist da! Ihr Kind ist begeistert, aber die Schlange ist aus dem Terrarium entkommen. Sie finden sie im Badezimmer."
    left:
      label: "Vorsichtig zurück ins Terrarium setzen"
      effects:
        - eltern_nerven: -20
        - kinder_glueck: +15
        - kinder_gesundheit: +5
    right:
      label: "Kind rufen - das ist sein Haustier!"
      effects:
        - kinder_glueck: +20
        - eltern_nerven: +10
        - kinder_gesundheit: -5
    probability: 0.8
    mix_in_next: 15