id: supermarkt_chaos
title: "Supermarkt Chaos"
description: "Alltägliche Herausforderungen beim Einkaufen mit Kindern."
trigger:
  after_cards: 10
trigger_cards:
  # This card appears in main deck and can trigger the supermarket chaos story
  - id: supermarkt_besuch
    image: kid.png
    description: "Wöchentlicher Supermarkt-Besuch steht an. Ihr Kind möchte unbedingt mitkommen, aber Sie wissen, wie das meist endet..."
    left:
      label: "Kind mitnehmen - wird schon gutgehen"
      effects:
        - eltern_nerven: -10
        - kinder_glueck: +15
      accept_story: supermarkt_chaos
    right:
      label: "Babysitter organisieren"
      effects:
        - geld: -15
        - eltern_nerven: +10
      reject_story: supermarkt_chaos
story_cards:
  # These cards only appear when the supermarket chaos story is accepted
  - id: schlafanzug_supermarkt
    image: kid.png
    description: "Ihr Kind läuft plötzlich im Schlafanzug durch den Supermarkt und weigert sich, normale Kleidung anzuziehen. Andere Eltern schauen irritiert."
    left:
      label: "Ignorieren und weitermachen"
      effects:
        - eltern_nerven: -15
        - kinder_glueck: +10
    right:
      label: "Kind nach Hause bringen"
      effects:
        - eltern_nerven: -20
        - geld: +10
        - kinder_glueck: -5
    probability: 0.75
    mix_in_next: 15
  - id: kind_schreit_suessigkeiten
    image: kid.png
    description: "An der Kasse: 'MAMA, ICH WILL GUMMIBÄRCHEN!' Ihr Kind wirft sich vor allen Leuten auf den Boden. Die Kassiererin schaut mitleidig."
    left:
      label: "Gummibärchen kaufen - heute nicht diskutieren"
      effects:
        - geld: -5
        - kinder_glueck: +12
        - eltern_nerven: +5
    right:
      label: "Standhaft bleiben"
      effects:
        - eltern_nerven: -25
        - kinder_glueck: -15
    probability: 0.60
    mix_in_next: 20
  - id: darf_ich_chips
    image: kid.png
    description: "'Mama, darf ich Chips?' Ihr Kind steht vor dem Snack-Regal und bettelt mit großen Augen. Es ist schon die fünfte Nachfrage heute."
    left:
      label: "Eine kleine Tüte ist okay"
      effects:
        - geld: -3
        - kinder_glueck: +15
    right:
      label: "Nein, wir haben zu Hause Obst"
      effects:
        - kinder_glueck: -10
        - kinder_gesundheit: +5
    probability: 0.80
    mix_in_next: 25
  - id: kind_findet_rubbellos
    image: kid.png
    description: "Ihr Kind findet ein Rubbellos auf dem Boden. 'Mama, können wir das rubbeln?' Es ist noch unbenutzt."
    left:
      label: "Rubbellos abgeben an der Information"
      effects:
        - kinder_glueck: -5
        - eltern_nerven: +5
    right:
      label: "Zusammen rubbeln"
      effects:
        - geld: +10
        - kinder_glueck: +12
        - eltern_nerven: -5
    probability: 0.25
    mix_in_next: 30
  - id: darf_ich_suessigkeiten
    image: kid.png
    title: "Emma möchte Süßigkeiten"
    description: "Ihr Kind fragt höflich: 'Darf ich bitte diese Süßigkeiten haben?' und hält eine Packung Gummibärchen hoch."
    left:
      label: "Ja, eine Kleinigkeit"
      effects:
        - geld: -5
        - kinder_glueck: +15
        - eltern_nerven: +5
        - kinder_gesundheit: -3
    right:
      label: "Nein, heute nicht"
      effects:
        - kinder_glueck: -10
        - eltern_nerven: -5
        - kinder_gesundheit: +8
    probability: 0.85
    mix_in_next: 15
  - id: darf_ich_kuscheltier
    image: kid.png
    title: "Mia sieht ein Kuscheltier"
    description: "Im Supermarkt gibt es eine kleine Auswahl an Kuscheltieren. Ihr Kind umarmt einen kleinen Teddybär: 'Der ist so süß! Darf ich den haben?'"
    left:
      label: "Okay, eins darf mit"
      effects:
        - geld: -12
        - kinder_glueck: +15
        - eltern_nerven: +5
    right:
      label: "Nein, wir haben genug Kuscheltiere"
      effects:
        - kinder_glueck: -15
        - eltern_nerven: -10
    probability: 0.60
    mix_in_next: 20
  - id: darf_ich_ueberraschungsei
    image: kid.png
    description: "An der Kasse entdeckt Ihr Kind die Überraschungseier: 'Mama/Papa, darf ich bitte eins haben? Nur eins!' Die Kassiererin wartet bereits."
    left:
      label: "Na gut, eins geht"
      effects:
        - geld: -3
        - kinder_glueck: +15
        - eltern_nerven: +5
        - kinder_gesundheit: -3
    right:
      label: "Heute nicht, Schatz"
      effects:
        - kinder_glueck: -12
        - eltern_nerven: -8
        - kinder_gesundheit: +5
    probability: 0.90
    mix_in_next: 10
  - id: darf_ich_pudding
    image: kid.png
    description: "In der Kühltheke entdeckt Ihr Kind glitzernden Kinderpudding: 'Ohhhh, guck mal! Glitzerpudding! Den MUSS ich haben!'"
    left:
      label: "Einmal Glitzerpudding, bitte"
      effects:
        - geld: -7
        - kinder_glueck: +12
        - eltern_nerven: +8
        - kinder_gesundheit: -5
    right:
      label: "Nein, wir haben zuhause was"
      effects:
        - kinder_glueck: -15
        - eltern_nerven: -10
        - kinder_gesundheit: +8
    probability: 0.70
    mix_in_next: 18
  - id: darf_ich_fertigkuchen
    image: kid.png
    description: "Ihr Kind zeigt begeistert auf einen bunten Fertigkuchen mit viel Zuckerguss: 'Wow! Den möchte ich haben! Der sieht so lecker aus!'"
    left:
      label: "Okay, aber nur diesmal"
      effects:
        - geld: -8
        - kinder_glueck: +12
        - eltern_nerven: +5
        - kinder_gesundheit: -5
    right:
      label: "Nein, das ist nur Zucker"
      effects:
        - geld: +3
        - kinder_glueck: -10
        - eltern_nerven: -8
        - kinder_gesundheit: +15
    probability: 0.75
    mix_in_next: 25
  - id: darf_ich_dosenfisch
    image: kid.png
    description: "Ihr Kind zeigt auf eine Dose Thunfisch und fragt: 'Darf ich das haben?' Sie sind verwirrt - normalerweise mag Ihr Kind keinen Fisch."
    left:
      label: "Ähm... okay?"
      effects:
        - geld: -4
        - kinder_glueck: +10
        - eltern_nerven: -5
        - kinder_gesundheit: +15
    right:
      label: "Lieber nicht, Fisch im Sommer..."
      effects:
        - kinder_glueck: -8
        - eltern_nerven: +10
        - kinder_gesundheit: +5
    probability: 0.40
    mix_in_next: 35